Gs                            Params    OutputShape         WeightShape
---                           ---       ---                 ---
latents_in                    -         (1, 512)            -
labels_in                     -         (1, 0)              -
lod                           -         ()                  -
dlatent_avg                   -         (512,)              -
G_mapping/latents_in          -         (1, 512)            -
G_mapping/labels_in           -         (1, 0)              -
G_mapping/PixelNorm           -         (1, 512)            -
G_mapping/Dense0              262656    (1, 512)            (512, 512)
G_mapping/Dense1              262656    (1, 512)            (512, 512)
G_mapping/Dense2              262656    (1, 512)            (512, 512)
G_mapping/Dense3              262656    (1, 512)            (512, 512)
G_mapping/Dense4              262656    (1, 512)            (512, 512)
G_mapping/Dense5              262656    (1, 512)            (512, 512)
G_mapping/Dense6              262656    (1, 512)            (512, 512)
G_mapping/Dense7              262656    (1, 512)            (512, 512)
G_mapping/Broadcast           -         (1, 16, 512)        -
G_mapping/dlatents_out        -         (1, 16, 512)        -
Truncation                    -         (1, 16, 512)        -
G_synthesis/dlatents_in       -         (1, 16, 512)        -
G_synthesis/4x4/Const         534528    (1, 512, 4, 4)      (512,)
G_synthesis/4x4/Conv          2885632   (1, 512, 4, 4)      (3, 3, 512, 512)
G_synthesis/ToRGB_lod7        1539      (1, 3, 4, 4)        (1, 1, 512, 3)
G_synthesis/8x8/Conv0_up      2885632   (1, 512, 8, 8)      (3, 3, 512, 512)
G_synthesis/8x8/Conv1         2885632   (1, 512, 8, 8)      (3, 3, 512, 512)
G_synthesis/ToRGB_lod6        1539      (1, 3, 8, 8)        (1, 1, 512, 3)
G_synthesis/Upscale2D         -         (1, 3, 8, 8)        -
G_synthesis/Grow_lod6         -         (1, 3, 8, 8)        -
G_synthesis/16x16/Conv0_up    2885632   (1, 512, 16, 16)    (3, 3, 512, 512)
G_synthesis/16x16/Conv1       2885632   (1, 512, 16, 16)    (3, 3, 512, 512)
G_synthesis/ToRGB_lod5        1539      (1, 3, 16, 16)      (1, 1, 512, 3)
G_synthesis/Upscale2D_1       -         (1, 3, 16, 16)      -
G_synthesis/Grow_lod5         -         (1, 3, 16, 16)      -
G_synthesis/32x32/Conv0_up    2885632   (1, 512, 32, 32)    (3, 3, 512, 512)
G_synthesis/32x32/Conv1       2885632   (1, 512, 32, 32)    (3, 3, 512, 512)
G_synthesis/ToRGB_lod4        1539      (1, 3, 32, 32)      (1, 1, 512, 3)
G_synthesis/Upscale2D_2       -         (1, 3, 32, 32)      -
G_synthesis/Grow_lod4         -         (1, 3, 32, 32)      -
G_synthesis/64x64/Conv0_up    1442816   (1, 256, 64, 64)    (3, 3, 512, 256)
G_synthesis/64x64/Conv1       852992    (1, 256, 64, 64)    (3, 3, 256, 256)
G_synthesis/ToRGB_lod3        771       (1, 3, 64, 64)      (1, 1, 256, 3)
G_synthesis/Upscale2D_3       -         (1, 3, 64, 64)      -
G_synthesis/Grow_lod3         -         (1, 3, 64, 64)      -
G_synthesis/128x128/Conv0_up  426496    (1, 128, 128, 128)  (3, 3, 256, 128)
G_synthesis/128x128/Conv1     279040    (1, 128, 128, 128)  (3, 3, 128, 128)
G_synthesis/ToRGB_lod2        387       (1, 3, 128, 128)    (1, 1, 128, 3)
G_synthesis/Upscale2D_4       -         (1, 3, 128, 128)    -
G_synthesis/Grow_lod2         -         (1, 3, 128, 128)    -
G_synthesis/256x256/Conv0_up  139520    (1, 64, 256, 256)   (3, 3, 128, 64)
G_synthesis/256x256/Conv1     102656    (1, 64, 256, 256)   (3, 3, 64, 64)
G_synthesis/ToRGB_lod1        195       (1, 3, 256, 256)    (1, 1, 64, 3)
G_synthesis/Upscale2D_5       -         (1, 3, 256, 256)    -
G_synthesis/Grow_lod1         -         (1, 3, 256, 256)    -
G_synthesis/512x512/Conv0_up  51328     (1, 32, 512, 512)   (3, 3, 64, 32)
G_synthesis/512x512/Conv1     42112     (1, 32, 512, 512)   (3, 3, 32, 32)
G_synthesis/ToRGB_lod0        99        (1, 3, 512, 512)    (1, 1, 32, 3)
G_synthesis/Upscale2D_6       -         (1, 3, 512, 512)    -
G_synthesis/Grow_lod0         -         (1, 3, 512, 512)    -
G_synthesis/images_out        -         (1, 3, 512, 512)    -
G_synthesis/lod               -         ()                  -
G_synthesis/noise0            -         (1, 1, 4, 4)        -
G_synthesis/noise1            -         (1, 1, 4, 4)        -
G_synthesis/noise2            -         (1, 1, 8, 8)        -
G_synthesis/noise3            -         (1, 1, 8, 8)        -
G_synthesis/noise4            -         (1, 1, 16, 16)      -
G_synthesis/noise5            -         (1, 1, 16, 16)      -
G_synthesis/noise6            -         (1, 1, 32, 32)      -
G_synthesis/noise7            -         (1, 1, 32, 32)      -
G_synthesis/noise8            -         (1, 1, 64, 64)      -
G_synthesis/noise9            -         (1, 1, 64, 64)      -
G_synthesis/noise10           -         (1, 1, 128, 128)    -
G_synthesis/noise11           -         (1, 1, 128, 128)    -
G_synthesis/noise12           -         (1, 1, 256, 256)    -
G_synthesis/noise13           -         (1, 1, 256, 256)    -
G_synthesis/noise14           -         (1, 1, 512, 512)    -
G_synthesis/noise15           -         (1, 1, 512, 512)    -
images_out                    -         (1, 3, 512, 512)    -
---                           ---       ---                 ---
Total                         26179768


[<tf.Operation 'Gs/latents_in' type=Placeholder>,
 <tf.Operation 'Gs/labels_in' type=Placeholder>,
 <tf.Operation 'Gs/lod/initial_value' type=Const>,
 <tf.Operation 'Gs/lod' type=VariableV2>,
 <tf.Operation 'Gs/lod/Assign' type=Assign>,
 <tf.Operation 'Gs/lod/read' type=Identity>,
 <tf.Operation 'Gs/dlatent_avg/Initializer/zeros' type=Const>,
 <tf.Operation 'Gs/dlatent_avg' type=VariableV2>,
 <tf.Operation 'Gs/dlatent_avg/Assign' type=Assign>,
 <tf.Operation 'Gs/dlatent_avg/read' type=Identity>,
 <tf.Operation 'Gs/G_mapping/latents_in' type=Identity>,
 <tf.Operation 'Gs/G_mapping/labels_in' type=Identity>,
 <tf.Operation 'Gs/G_mapping/PixelNorm/epsilon' type=Const>,
 <tf.Operation 'Gs/G_mapping/PixelNorm/Square' type=Square>,
 <tf.Operation 'Gs/G_mapping/PixelNorm/Mean/reduction_indices' type=Const>,
 <tf.Operation 'Gs/G_mapping/PixelNorm/Mean' type=Mean>,
 <tf.Operation 'Gs/G_mapping/PixelNorm/add' type=Add>,
 <tf.Operation 'Gs/G_mapping/PixelNorm/Rsqrt' type=Rsqrt>,
 <tf.Operation 'Gs/G_mapping/PixelNorm/mul' type=Mul>,
 <tf.Operation 'Gs/G_mapping/Dense0/mul/y' type=Const>,
 <tf.Operation 'Gs/G_mapping/Dense0/mul' type=Mul>,
 <tf.Operation 'Gs/G_mapping/Dense0/MatMul' type=MatMul>,
 <tf.Operation 'Gs/G_mapping/Dense0/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_mapping/Dense0/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_mapping/Dense0/add' type=Add>,
 <tf.Operation 'Gs/G_mapping/Dense0/LeakyReLU/alpha' type=Const>,
 <tf.Operation 'Gs/G_mapping/Dense0/LeakyReLU/mul' type=Mul>,
 <tf.Operation 'Gs/G_mapping/Dense0/LeakyReLU/Maximum' type=Maximum>,
 <tf.Operation 'Gs/G_mapping/Dense0/LeakyReLU/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_mapping/Dense1/mul/y' type=Const>,
 <tf.Operation 'Gs/G_mapping/Dense1/mul' type=Mul>,
 <tf.Operation 'Gs/G_mapping/Dense1/MatMul' type=MatMul>,
 <tf.Operation 'Gs/G_mapping/Dense1/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_mapping/Dense1/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_mapping/Dense1/add' type=Add>,
 <tf.Operation 'Gs/G_mapping/Dense1/LeakyReLU/alpha' type=Const>,
 <tf.Operation 'Gs/G_mapping/Dense1/LeakyReLU/mul' type=Mul>,
 <tf.Operation 'Gs/G_mapping/Dense1/LeakyReLU/Maximum' type=Maximum>,
 <tf.Operation 'Gs/G_mapping/Dense1/LeakyReLU/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_mapping/Dense2/mul/y' type=Const>,
 <tf.Operation 'Gs/G_mapping/Dense2/mul' type=Mul>,
 <tf.Operation 'Gs/G_mapping/Dense2/MatMul' type=MatMul>,
 <tf.Operation 'Gs/G_mapping/Dense2/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_mapping/Dense2/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_mapping/Dense2/add' type=Add>,
 <tf.Operation 'Gs/G_mapping/Dense2/LeakyReLU/alpha' type=Const>,
 <tf.Operation 'Gs/G_mapping/Dense2/LeakyReLU/mul' type=Mul>,
 <tf.Operation 'Gs/G_mapping/Dense2/LeakyReLU/Maximum' type=Maximum>,
 <tf.Operation 'Gs/G_mapping/Dense2/LeakyReLU/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_mapping/Dense3/mul/y' type=Const>,
 <tf.Operation 'Gs/G_mapping/Dense3/mul' type=Mul>,
 <tf.Operation 'Gs/G_mapping/Dense3/MatMul' type=MatMul>,
 <tf.Operation 'Gs/G_mapping/Dense3/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_mapping/Dense3/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_mapping/Dense3/add' type=Add>,
 <tf.Operation 'Gs/G_mapping/Dense3/LeakyReLU/alpha' type=Const>,
 <tf.Operation 'Gs/G_mapping/Dense3/LeakyReLU/mul' type=Mul>,
 <tf.Operation 'Gs/G_mapping/Dense3/LeakyReLU/Maximum' type=Maximum>,
 <tf.Operation 'Gs/G_mapping/Dense3/LeakyReLU/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_mapping/Dense4/mul/y' type=Const>,
 <tf.Operation 'Gs/G_mapping/Dense4/mul' type=Mul>,
 <tf.Operation 'Gs/G_mapping/Dense4/MatMul' type=MatMul>,
 <tf.Operation 'Gs/G_mapping/Dense4/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_mapping/Dense4/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_mapping/Dense4/add' type=Add>,
 <tf.Operation 'Gs/G_mapping/Dense4/LeakyReLU/alpha' type=Const>,
 <tf.Operation 'Gs/G_mapping/Dense4/LeakyReLU/mul' type=Mul>,
 <tf.Operation 'Gs/G_mapping/Dense4/LeakyReLU/Maximum' type=Maximum>,
 <tf.Operation 'Gs/G_mapping/Dense4/LeakyReLU/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_mapping/Dense5/mul/y' type=Const>,
 <tf.Operation 'Gs/G_mapping/Dense5/mul' type=Mul>,
 <tf.Operation 'Gs/G_mapping/Dense5/MatMul' type=MatMul>,
 <tf.Operation 'Gs/G_mapping/Dense5/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_mapping/Dense5/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_mapping/Dense5/add' type=Add>,
 <tf.Operation 'Gs/G_mapping/Dense5/LeakyReLU/alpha' type=Const>,
 <tf.Operation 'Gs/G_mapping/Dense5/LeakyReLU/mul' type=Mul>,
 <tf.Operation 'Gs/G_mapping/Dense5/LeakyReLU/Maximum' type=Maximum>,
 <tf.Operation 'Gs/G_mapping/Dense5/LeakyReLU/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_mapping/Dense6/mul/y' type=Const>,
 <tf.Operation 'Gs/G_mapping/Dense6/mul' type=Mul>,
 <tf.Operation 'Gs/G_mapping/Dense6/MatMul' type=MatMul>,
 <tf.Operation 'Gs/G_mapping/Dense6/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_mapping/Dense6/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_mapping/Dense6/add' type=Add>,
 <tf.Operation 'Gs/G_mapping/Dense6/LeakyReLU/alpha' type=Const>,
 <tf.Operation 'Gs/G_mapping/Dense6/LeakyReLU/mul' type=Mul>,
 <tf.Operation 'Gs/G_mapping/Dense6/LeakyReLU/Maximum' type=Maximum>,
 <tf.Operation 'Gs/G_mapping/Dense6/LeakyReLU/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_mapping/Dense7/mul/y' type=Const>,
 <tf.Operation 'Gs/G_mapping/Dense7/mul' type=Mul>,
 <tf.Operation 'Gs/G_mapping/Dense7/MatMul' type=MatMul>,
 <tf.Operation 'Gs/G_mapping/Dense7/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_mapping/Dense7/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_mapping/Dense7/add' type=Add>,
 <tf.Operation 'Gs/G_mapping/Dense7/LeakyReLU/alpha' type=Const>,
 <tf.Operation 'Gs/G_mapping/Dense7/LeakyReLU/mul' type=Mul>,
 <tf.Operation 'Gs/G_mapping/Dense7/LeakyReLU/Maximum' type=Maximum>,
 <tf.Operation 'Gs/G_mapping/Dense7/LeakyReLU/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_mapping/Broadcast/strided_slice/stack' type=Const>,
 <tf.Operation 'Gs/G_mapping/Broadcast/strided_slice/stack_1' type=Const>,
 <tf.Operation 'Gs/G_mapping/Broadcast/strided_slice/stack_2' type=Const>,
 <tf.Operation 'Gs/G_mapping/Broadcast/strided_slice' type=StridedSlice>,
 <tf.Operation 'Gs/G_mapping/Broadcast/Tile/multiples' type=Const>,
 <tf.Operation 'Gs/G_mapping/Broadcast/Tile' type=Tile>,
 <tf.Operation 'Gs/G_mapping/dlatents_out' type=Identity>,
 <tf.Operation 'Gs/Truncation/Select/condition' type=Const>,
 <tf.Operation 'Gs/Truncation/Select/t' type=Const>,
 <tf.Operation 'Gs/Truncation/Select/e' type=Const>,
 <tf.Operation 'Gs/Truncation/Select' type=Select>,
 <tf.Operation 'Gs/Truncation/Lerp/sub' type=Sub>,
 <tf.Operation 'Gs/Truncation/Lerp/mul' type=Mul>,
 <tf.Operation 'Gs/Truncation/Lerp/add' type=Add>,
 <tf.Operation 'Gs/Assign' type=Assign>,
 <tf.Operation 'Gs/G_synthesis/dlatents_in' type=Identity>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/Shape' type=Shape>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/strided_slice/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/strided_slice/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/strided_slice/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/strided_slice' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/Tile/multiples/1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/Tile/multiples/2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/Tile/multiples/3' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/Tile/multiples' type=Pack>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/Tile' type=Tile>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/Noise/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/Noise/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/Noise/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/Noise/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/mul/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/LeakyReLU/alpha' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/LeakyReLU/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/LeakyReLU/Maximum' type=Maximum>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/LeakyReLU/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/InstanceNorm/Mean/reduction_indices' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/InstanceNorm/Mean' type=Mean>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/InstanceNorm/sub' type=Sub>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/InstanceNorm/epsilon' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/InstanceNorm/Square' type=Square>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/InstanceNorm/Mean_1/reduction_indices' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/InstanceNorm/Mean_1' type=Mean>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/InstanceNorm/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/InstanceNorm/Rsqrt' type=Rsqrt>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/InstanceNorm/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/strided_slice_1/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/strided_slice_1/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/strided_slice_1/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/strided_slice_1' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/StyleMod/mul/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/StyleMod/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/StyleMod/MatMul' type=MatMul>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/StyleMod/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/StyleMod/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/StyleMod/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/StyleMod/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/StyleMod/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/StyleMod/strided_slice/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/StyleMod/strided_slice/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/StyleMod/strided_slice/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/StyleMod/strided_slice' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/StyleMod/add_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/StyleMod/add_1' type=Add>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/StyleMod/mul_2' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/StyleMod/strided_slice_1/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/StyleMod/strided_slice_1/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/StyleMod/strided_slice_1/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/StyleMod/strided_slice_1' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/4x4/Const/StyleMod/add_2' type=Add>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/mul/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/Conv2D' type=Conv2D>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/Noise/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/Noise/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/Noise/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/Noise/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/LeakyReLU/alpha' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/LeakyReLU/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/LeakyReLU/Maximum' type=Maximum>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/LeakyReLU/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/InstanceNorm/Mean/reduction_indices' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/InstanceNorm/Mean' type=Mean>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/InstanceNorm/sub' type=Sub>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/InstanceNorm/epsilon' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/InstanceNorm/Square' type=Square>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/InstanceNorm/Mean_1/reduction_indices' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/InstanceNorm/Mean_1' type=Mean>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/InstanceNorm/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/InstanceNorm/Rsqrt' type=Rsqrt>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/InstanceNorm/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/strided_slice/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/strided_slice/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/strided_slice/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/strided_slice' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/StyleMod/mul/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/StyleMod/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/StyleMod/MatMul' type=MatMul>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/StyleMod/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/StyleMod/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/StyleMod/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/StyleMod/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/StyleMod/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/StyleMod/strided_slice/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/StyleMod/strided_slice/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/StyleMod/strided_slice/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/StyleMod/strided_slice' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/StyleMod/add_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/StyleMod/add_1' type=Add>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/StyleMod/mul_2' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/StyleMod/strided_slice_1/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/StyleMod/strided_slice_1/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/StyleMod/strided_slice_1/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/StyleMod/strided_slice_1' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/4x4/Conv/StyleMod/add_2' type=Add>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod7/mul/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod7/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod7/Conv2D' type=Conv2D>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod7/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod7/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod7/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod7/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod7/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/Upscale2D/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/Upscale2D/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/Upscale2D/Tile/multiples' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/Upscale2D/Tile' type=Tile>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/Upscale2D/Reshape_1/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/Upscale2D/Reshape_1' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/Upscale2D/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/mul/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/Conv2D' type=Conv2D>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/Blur2D/filter' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/Blur2D/depthwise/Shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/Blur2D/depthwise/dilation_rate' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/Blur2D/depthwise' type=DepthwiseConv2dNative>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/Blur2D/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/Noise/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/Noise/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/Noise/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/Noise/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/LeakyReLU/alpha' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/LeakyReLU/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/LeakyReLU/Maximum' type=Maximum>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/LeakyReLU/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/InstanceNorm/Mean/reduction_indices' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/InstanceNorm/Mean' type=Mean>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/InstanceNorm/sub' type=Sub>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/InstanceNorm/epsilon' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/InstanceNorm/Square' type=Square>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/InstanceNorm/Mean_1/reduction_indices' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/InstanceNorm/Mean_1' type=Mean>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/InstanceNorm/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/InstanceNorm/Rsqrt' type=Rsqrt>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/InstanceNorm/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/strided_slice/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/strided_slice/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/strided_slice/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/strided_slice' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/StyleMod/mul/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/StyleMod/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/StyleMod/MatMul' type=MatMul>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/StyleMod/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/StyleMod/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/StyleMod/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/StyleMod/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/StyleMod/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/StyleMod/strided_slice/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/StyleMod/strided_slice/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/StyleMod/strided_slice/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/StyleMod/strided_slice' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/StyleMod/add_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/StyleMod/add_1' type=Add>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/StyleMod/mul_2' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/StyleMod/strided_slice_1/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/StyleMod/strided_slice_1/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/StyleMod/strided_slice_1/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/StyleMod/strided_slice_1' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv0_up/StyleMod/add_2' type=Add>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/mul/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/Conv2D' type=Conv2D>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/Noise/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/Noise/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/Noise/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/Noise/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/LeakyReLU/alpha' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/LeakyReLU/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/LeakyReLU/Maximum' type=Maximum>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/LeakyReLU/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/InstanceNorm/Mean/reduction_indices' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/InstanceNorm/Mean' type=Mean>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/InstanceNorm/sub' type=Sub>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/InstanceNorm/epsilon' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/InstanceNorm/Square' type=Square>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/InstanceNorm/Mean_1/reduction_indices' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/InstanceNorm/Mean_1' type=Mean>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/InstanceNorm/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/InstanceNorm/Rsqrt' type=Rsqrt>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/InstanceNorm/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/strided_slice/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/strided_slice/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/strided_slice/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/strided_slice' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/StyleMod/mul/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/StyleMod/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/StyleMod/MatMul' type=MatMul>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/StyleMod/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/StyleMod/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/StyleMod/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/StyleMod/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/StyleMod/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/StyleMod/strided_slice/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/StyleMod/strided_slice/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/StyleMod/strided_slice/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/StyleMod/strided_slice' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/StyleMod/add_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/StyleMod/add_1' type=Add>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/StyleMod/mul_2' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/StyleMod/strided_slice_1/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/StyleMod/strided_slice_1/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/StyleMod/strided_slice_1/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/StyleMod/strided_slice_1' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/8x8/Conv1/StyleMod/add_2' type=Add>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod6/mul/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod6/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod6/Conv2D' type=Conv2D>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod6/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod6/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod6/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod6/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod6/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D/Tile/multiples' type=Const>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D/Tile' type=Tile>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D/Reshape_1/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D/Reshape_1' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod6/sub/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod6/sub' type=Sub>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod6/LerpClip/sub' type=Sub>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod6/LerpClip/clip_by_value/Minimum/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod6/LerpClip/clip_by_value/Minimum' type=Minimum>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod6/LerpClip/clip_by_value/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod6/LerpClip/clip_by_value' type=Maximum>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod6/LerpClip/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod6/LerpClip/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/Upscale2D/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/Upscale2D/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/Upscale2D/Tile/multiples' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/Upscale2D/Tile' type=Tile>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/Upscale2D/Reshape_1/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/Upscale2D/Reshape_1' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/Upscale2D/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/mul/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/Conv2D' type=Conv2D>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/Blur2D/filter' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/Blur2D/depthwise/Shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/Blur2D/depthwise/dilation_rate' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/Blur2D/depthwise' type=DepthwiseConv2dNative>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/Blur2D/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/Noise/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/Noise/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/Noise/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/Noise/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/LeakyReLU/alpha' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/LeakyReLU/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/LeakyReLU/Maximum' type=Maximum>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/LeakyReLU/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/InstanceNorm/Mean/reduction_indices' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/InstanceNorm/Mean' type=Mean>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/InstanceNorm/sub' type=Sub>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/InstanceNorm/epsilon' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/InstanceNorm/Square' type=Square>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/InstanceNorm/Mean_1/reduction_indices' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/InstanceNorm/Mean_1' type=Mean>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/InstanceNorm/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/InstanceNorm/Rsqrt' type=Rsqrt>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/InstanceNorm/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/strided_slice/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/strided_slice/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/strided_slice/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/strided_slice' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/StyleMod/mul/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/StyleMod/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/StyleMod/MatMul' type=MatMul>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/StyleMod/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/StyleMod/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/StyleMod/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/StyleMod/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/StyleMod/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/StyleMod/strided_slice/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/StyleMod/strided_slice/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/StyleMod/strided_slice/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/StyleMod/strided_slice' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/StyleMod/add_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/StyleMod/add_1' type=Add>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/StyleMod/mul_2' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/StyleMod/strided_slice_1/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/StyleMod/strided_slice_1/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/StyleMod/strided_slice_1/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/StyleMod/strided_slice_1' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv0_up/StyleMod/add_2' type=Add>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/mul/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/Conv2D' type=Conv2D>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/Noise/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/Noise/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/Noise/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/Noise/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/LeakyReLU/alpha' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/LeakyReLU/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/LeakyReLU/Maximum' type=Maximum>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/LeakyReLU/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/InstanceNorm/Mean/reduction_indices' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/InstanceNorm/Mean' type=Mean>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/InstanceNorm/sub' type=Sub>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/InstanceNorm/epsilon' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/InstanceNorm/Square' type=Square>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/InstanceNorm/Mean_1/reduction_indices' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/InstanceNorm/Mean_1' type=Mean>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/InstanceNorm/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/InstanceNorm/Rsqrt' type=Rsqrt>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/InstanceNorm/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/strided_slice/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/strided_slice/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/strided_slice/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/strided_slice' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/StyleMod/mul/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/StyleMod/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/StyleMod/MatMul' type=MatMul>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/StyleMod/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/StyleMod/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/StyleMod/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/StyleMod/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/StyleMod/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/StyleMod/strided_slice/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/StyleMod/strided_slice/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/StyleMod/strided_slice/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/StyleMod/strided_slice' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/StyleMod/add_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/StyleMod/add_1' type=Add>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/StyleMod/mul_2' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/StyleMod/strided_slice_1/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/StyleMod/strided_slice_1/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/StyleMod/strided_slice_1/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/StyleMod/strided_slice_1' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/16x16/Conv1/StyleMod/add_2' type=Add>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod5/mul/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod5/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod5/Conv2D' type=Conv2D>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod5/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod5/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod5/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod5/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod5/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D_1/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D_1/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D_1/Tile/multiples' type=Const>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D_1/Tile' type=Tile>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D_1/Reshape_1/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D_1/Reshape_1' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D_1/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod5/sub/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod5/sub' type=Sub>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod5/LerpClip/sub' type=Sub>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod5/LerpClip/clip_by_value/Minimum/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod5/LerpClip/clip_by_value/Minimum' type=Minimum>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod5/LerpClip/clip_by_value/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod5/LerpClip/clip_by_value' type=Maximum>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod5/LerpClip/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod5/LerpClip/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/Upscale2D/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/Upscale2D/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/Upscale2D/Tile/multiples' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/Upscale2D/Tile' type=Tile>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/Upscale2D/Reshape_1/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/Upscale2D/Reshape_1' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/Upscale2D/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/mul/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/Conv2D' type=Conv2D>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/Blur2D/filter' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/Blur2D/depthwise/Shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/Blur2D/depthwise/dilation_rate' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/Blur2D/depthwise' type=DepthwiseConv2dNative>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/Blur2D/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/Noise/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/Noise/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/Noise/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/Noise/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/LeakyReLU/alpha' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/LeakyReLU/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/LeakyReLU/Maximum' type=Maximum>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/LeakyReLU/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/InstanceNorm/Mean/reduction_indices' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/InstanceNorm/Mean' type=Mean>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/InstanceNorm/sub' type=Sub>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/InstanceNorm/epsilon' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/InstanceNorm/Square' type=Square>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/InstanceNorm/Mean_1/reduction_indices' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/InstanceNorm/Mean_1' type=Mean>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/InstanceNorm/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/InstanceNorm/Rsqrt' type=Rsqrt>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/InstanceNorm/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/strided_slice/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/strided_slice/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/strided_slice/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/strided_slice' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/StyleMod/mul/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/StyleMod/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/StyleMod/MatMul' type=MatMul>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/StyleMod/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/StyleMod/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/StyleMod/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/StyleMod/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/StyleMod/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/StyleMod/strided_slice/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/StyleMod/strided_slice/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/StyleMod/strided_slice/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/StyleMod/strided_slice' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/StyleMod/add_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/StyleMod/add_1' type=Add>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/StyleMod/mul_2' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/StyleMod/strided_slice_1/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/StyleMod/strided_slice_1/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/StyleMod/strided_slice_1/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/StyleMod/strided_slice_1' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv0_up/StyleMod/add_2' type=Add>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/mul/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/Conv2D' type=Conv2D>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/Noise/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/Noise/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/Noise/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/Noise/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/LeakyReLU/alpha' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/LeakyReLU/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/LeakyReLU/Maximum' type=Maximum>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/LeakyReLU/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/InstanceNorm/Mean/reduction_indices' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/InstanceNorm/Mean' type=Mean>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/InstanceNorm/sub' type=Sub>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/InstanceNorm/epsilon' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/InstanceNorm/Square' type=Square>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/InstanceNorm/Mean_1/reduction_indices' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/InstanceNorm/Mean_1' type=Mean>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/InstanceNorm/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/InstanceNorm/Rsqrt' type=Rsqrt>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/InstanceNorm/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/strided_slice/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/strided_slice/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/strided_slice/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/strided_slice' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/StyleMod/mul/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/StyleMod/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/StyleMod/MatMul' type=MatMul>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/StyleMod/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/StyleMod/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/StyleMod/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/StyleMod/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/StyleMod/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/StyleMod/strided_slice/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/StyleMod/strided_slice/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/StyleMod/strided_slice/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/StyleMod/strided_slice' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/StyleMod/add_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/StyleMod/add_1' type=Add>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/StyleMod/mul_2' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/StyleMod/strided_slice_1/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/StyleMod/strided_slice_1/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/StyleMod/strided_slice_1/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/StyleMod/strided_slice_1' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/32x32/Conv1/StyleMod/add_2' type=Add>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod4/mul/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod4/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod4/Conv2D' type=Conv2D>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod4/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod4/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod4/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod4/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod4/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D_2/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D_2/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D_2/Tile/multiples' type=Const>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D_2/Tile' type=Tile>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D_2/Reshape_1/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D_2/Reshape_1' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D_2/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod4/sub/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod4/sub' type=Sub>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod4/LerpClip/sub' type=Sub>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod4/LerpClip/clip_by_value/Minimum/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod4/LerpClip/clip_by_value/Minimum' type=Minimum>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod4/LerpClip/clip_by_value/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod4/LerpClip/clip_by_value' type=Maximum>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod4/LerpClip/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod4/LerpClip/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/Upscale2D/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/Upscale2D/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/Upscale2D/Tile/multiples' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/Upscale2D/Tile' type=Tile>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/Upscale2D/Reshape_1/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/Upscale2D/Reshape_1' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/Upscale2D/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/mul/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/Conv2D' type=Conv2D>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/Blur2D/filter' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/Blur2D/depthwise/Shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/Blur2D/depthwise/dilation_rate' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/Blur2D/depthwise' type=DepthwiseConv2dNative>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/Blur2D/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/Noise/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/Noise/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/Noise/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/Noise/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/LeakyReLU/alpha' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/LeakyReLU/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/LeakyReLU/Maximum' type=Maximum>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/LeakyReLU/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/InstanceNorm/Mean/reduction_indices' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/InstanceNorm/Mean' type=Mean>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/InstanceNorm/sub' type=Sub>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/InstanceNorm/epsilon' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/InstanceNorm/Square' type=Square>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/InstanceNorm/Mean_1/reduction_indices' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/InstanceNorm/Mean_1' type=Mean>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/InstanceNorm/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/InstanceNorm/Rsqrt' type=Rsqrt>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/InstanceNorm/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/strided_slice/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/strided_slice/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/strided_slice/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/strided_slice' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/StyleMod/mul/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/StyleMod/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/StyleMod/MatMul' type=MatMul>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/StyleMod/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/StyleMod/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/StyleMod/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/StyleMod/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/StyleMod/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/StyleMod/strided_slice/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/StyleMod/strided_slice/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/StyleMod/strided_slice/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/StyleMod/strided_slice' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/StyleMod/add_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/StyleMod/add_1' type=Add>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/StyleMod/mul_2' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/StyleMod/strided_slice_1/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/StyleMod/strided_slice_1/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/StyleMod/strided_slice_1/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/StyleMod/strided_slice_1' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv0_up/StyleMod/add_2' type=Add>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/mul/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/Conv2D' type=Conv2D>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/Noise/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/Noise/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/Noise/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/Noise/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/LeakyReLU/alpha' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/LeakyReLU/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/LeakyReLU/Maximum' type=Maximum>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/LeakyReLU/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/InstanceNorm/Mean/reduction_indices' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/InstanceNorm/Mean' type=Mean>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/InstanceNorm/sub' type=Sub>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/InstanceNorm/epsilon' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/InstanceNorm/Square' type=Square>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/InstanceNorm/Mean_1/reduction_indices' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/InstanceNorm/Mean_1' type=Mean>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/InstanceNorm/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/InstanceNorm/Rsqrt' type=Rsqrt>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/InstanceNorm/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/strided_slice/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/strided_slice/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/strided_slice/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/strided_slice' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/StyleMod/mul/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/StyleMod/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/StyleMod/MatMul' type=MatMul>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/StyleMod/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/StyleMod/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/StyleMod/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/StyleMod/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/StyleMod/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/StyleMod/strided_slice/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/StyleMod/strided_slice/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/StyleMod/strided_slice/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/StyleMod/strided_slice' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/StyleMod/add_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/StyleMod/add_1' type=Add>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/StyleMod/mul_2' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/StyleMod/strided_slice_1/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/StyleMod/strided_slice_1/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/StyleMod/strided_slice_1/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/StyleMod/strided_slice_1' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/64x64/Conv1/StyleMod/add_2' type=Add>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod3/mul/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod3/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod3/Conv2D' type=Conv2D>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod3/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod3/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod3/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod3/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod3/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D_3/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D_3/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D_3/Tile/multiples' type=Const>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D_3/Tile' type=Tile>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D_3/Reshape_1/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D_3/Reshape_1' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D_3/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod3/sub/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod3/sub' type=Sub>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod3/LerpClip/sub' type=Sub>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod3/LerpClip/clip_by_value/Minimum/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod3/LerpClip/clip_by_value/Minimum' type=Minimum>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod3/LerpClip/clip_by_value/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod3/LerpClip/clip_by_value' type=Maximum>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod3/LerpClip/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod3/LerpClip/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/mul/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/transpose/perm' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/transpose' type=Transpose>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/Pad/paddings' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/Pad' type=Pad>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/strided_slice/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/strided_slice/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/strided_slice/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/strided_slice' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/strided_slice_1/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/strided_slice_1/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/strided_slice_1/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/strided_slice_1' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/strided_slice_2/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/strided_slice_2/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/strided_slice_2/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/strided_slice_2' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/strided_slice_3/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/strided_slice_3/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/strided_slice_3/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/strided_slice_3' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/AddN' type=AddN>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/Shape' type=Shape>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/strided_slice_4/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/strided_slice_4/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/strided_slice_4/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/strided_slice_4' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/conv2d_transpose/output_shape/1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/conv2d_transpose/output_shape/2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/conv2d_transpose/output_shape/3' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/conv2d_transpose/output_shape' type=Pack>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/conv2d_transpose' type=Conv2DBackpropInput>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/Blur2D/filter' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/Blur2D/depthwise/Shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/Blur2D/depthwise/dilation_rate' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/Blur2D/depthwise' type=DepthwiseConv2dNative>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/Blur2D/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/Noise/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/Noise/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/Noise/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/Noise/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/LeakyReLU/alpha' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/LeakyReLU/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/LeakyReLU/Maximum' type=Maximum>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/LeakyReLU/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/InstanceNorm/Mean/reduction_indices' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/InstanceNorm/Mean' type=Mean>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/InstanceNorm/sub' type=Sub>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/InstanceNorm/epsilon' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/InstanceNorm/Square' type=Square>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/InstanceNorm/Mean_1/reduction_indices' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/InstanceNorm/Mean_1' type=Mean>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/InstanceNorm/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/InstanceNorm/Rsqrt' type=Rsqrt>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/InstanceNorm/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/strided_slice_5/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/strided_slice_5/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/strided_slice_5/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/strided_slice_5' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/StyleMod/mul/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/StyleMod/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/StyleMod/MatMul' type=MatMul>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/StyleMod/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/StyleMod/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/StyleMod/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/StyleMod/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/StyleMod/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/StyleMod/strided_slice/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/StyleMod/strided_slice/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/StyleMod/strided_slice/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/StyleMod/strided_slice' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/StyleMod/add_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/StyleMod/add_1' type=Add>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/StyleMod/mul_2' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/StyleMod/strided_slice_1/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/StyleMod/strided_slice_1/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/StyleMod/strided_slice_1/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/StyleMod/strided_slice_1' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv0_up/StyleMod/add_2' type=Add>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/mul/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/Conv2D' type=Conv2D>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/Noise/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/Noise/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/Noise/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/Noise/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/LeakyReLU/alpha' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/LeakyReLU/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/LeakyReLU/Maximum' type=Maximum>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/LeakyReLU/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/InstanceNorm/Mean/reduction_indices' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/InstanceNorm/Mean' type=Mean>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/InstanceNorm/sub' type=Sub>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/InstanceNorm/epsilon' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/InstanceNorm/Square' type=Square>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/InstanceNorm/Mean_1/reduction_indices' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/InstanceNorm/Mean_1' type=Mean>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/InstanceNorm/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/InstanceNorm/Rsqrt' type=Rsqrt>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/InstanceNorm/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/strided_slice/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/strided_slice/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/strided_slice/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/strided_slice' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/StyleMod/mul/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/StyleMod/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/StyleMod/MatMul' type=MatMul>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/StyleMod/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/StyleMod/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/StyleMod/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/StyleMod/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/StyleMod/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/StyleMod/strided_slice/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/StyleMod/strided_slice/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/StyleMod/strided_slice/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/StyleMod/strided_slice' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/StyleMod/add_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/StyleMod/add_1' type=Add>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/StyleMod/mul_2' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/StyleMod/strided_slice_1/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/StyleMod/strided_slice_1/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/StyleMod/strided_slice_1/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/StyleMod/strided_slice_1' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/128x128/Conv1/StyleMod/add_2' type=Add>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod2/mul/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod2/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod2/Conv2D' type=Conv2D>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod2/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod2/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod2/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod2/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/ToRGB_lod2/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D_4/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D_4/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D_4/Tile/multiples' type=Const>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D_4/Tile' type=Tile>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D_4/Reshape_1/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D_4/Reshape_1' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/Upscale2D_4/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod2/sub/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod2/sub' type=Sub>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod2/LerpClip/sub' type=Sub>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod2/LerpClip/clip_by_value/Minimum/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod2/LerpClip/clip_by_value/Minimum' type=Minimum>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod2/LerpClip/clip_by_value/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod2/LerpClip/clip_by_value' type=Maximum>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod2/LerpClip/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/Grow_lod2/LerpClip/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/mul/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/transpose/perm' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/transpose' type=Transpose>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/Pad/paddings' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/Pad' type=Pad>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/strided_slice/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/strided_slice/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/strided_slice/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/strided_slice' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/strided_slice_1/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/strided_slice_1/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/strided_slice_1/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/strided_slice_1' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/strided_slice_2/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/strided_slice_2/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/strided_slice_2/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/strided_slice_2' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/strided_slice_3/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/strided_slice_3/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/strided_slice_3/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/strided_slice_3' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/AddN' type=AddN>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/Shape' type=Shape>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/strided_slice_4/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/strided_slice_4/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/strided_slice_4/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/strided_slice_4' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/conv2d_transpose/output_shape/1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/conv2d_transpose/output_shape/2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/conv2d_transpose/output_shape/3' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/conv2d_transpose/output_shape' type=Pack>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/conv2d_transpose' type=Conv2DBackpropInput>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/Blur2D/filter' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/Blur2D/depthwise/Shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/Blur2D/depthwise/dilation_rate' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/Blur2D/depthwise' type=DepthwiseConv2dNative>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/Blur2D/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/Noise/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/Noise/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/Noise/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/Noise/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/mul_1/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/mul_1' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/Reshape/shape' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/Reshape' type=Reshape>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/LeakyReLU/alpha' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/LeakyReLU/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/LeakyReLU/Maximum' type=Maximum>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/LeakyReLU/IdentityN' type=IdentityN>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/InstanceNorm/Mean/reduction_indices' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/InstanceNorm/Mean' type=Mean>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/InstanceNorm/sub' type=Sub>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/InstanceNorm/epsilon' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/InstanceNorm/Square' type=Square>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/InstanceNorm/Mean_1/reduction_indices' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/InstanceNorm/Mean_1' type=Mean>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/InstanceNorm/add' type=Add>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/InstanceNorm/Rsqrt' type=Rsqrt>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/InstanceNorm/mul' type=Mul>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/strided_slice_5/stack' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/strided_slice_5/stack_1' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/strided_slice_5/stack_2' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/strided_slice_5' type=StridedSlice>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/StyleMod/mul/y' type=Const>,
 <tf.Operation 'Gs/G_synthesis/256x256/Conv0_up/StyleMod/mul' type=Mul>,
 ...]
 
 
 
 
 
 
 
 OrderedDict([('Gs/lod', 'lod'),
             ('Gs/dlatent_avg', 'dlatent_avg'),
             ('G_synthesis_1/lod', 'G_synthesis/lod'),
             ('G_synthesis_1/noise0', 'G_synthesis/noise0'),
             ('G_synthesis_1/noise1', 'G_synthesis/noise1'),
             ('G_synthesis_1/noise2', 'G_synthesis/noise2'),
             ('G_synthesis_1/noise3', 'G_synthesis/noise3'),
             ('G_synthesis_1/noise4', 'G_synthesis/noise4'),
             ('G_synthesis_1/noise5', 'G_synthesis/noise5'),
             ('G_synthesis_1/noise6', 'G_synthesis/noise6'),
             ('G_synthesis_1/noise7', 'G_synthesis/noise7'),
             ('G_synthesis_1/noise8', 'G_synthesis/noise8'),
             ('G_synthesis_1/noise9', 'G_synthesis/noise9'),
             ('G_synthesis_1/noise10', 'G_synthesis/noise10'),
             ('G_synthesis_1/noise11', 'G_synthesis/noise11'),
             ('G_synthesis_1/noise12', 'G_synthesis/noise12'),
             ('G_synthesis_1/noise13', 'G_synthesis/noise13'),
             ('G_synthesis_1/noise14', 'G_synthesis/noise14'),
             ('G_synthesis_1/noise15', 'G_synthesis/noise15'),
             ('G_synthesis_1/4x4/Const/const', 'G_synthesis/4x4/Const/const'),
             ('G_synthesis_1/4x4/Const/Noise/weight',
              'G_synthesis/4x4/Const/Noise/weight'),
             ('G_synthesis_1/4x4/Const/bias', 'G_synthesis/4x4/Const/bias'),
             ('G_synthesis_1/4x4/Const/StyleMod/weight',
              'G_synthesis/4x4/Const/StyleMod/weight'),
             ('G_synthesis_1/4x4/Const/StyleMod/bias',
              'G_synthesis/4x4/Const/StyleMod/bias'),
             ('G_synthesis_1/4x4/Conv/weight', 'G_synthesis/4x4/Conv/weight'),
             ('G_synthesis_1/4x4/Conv/Noise/weight',
              'G_synthesis/4x4/Conv/Noise/weight'),
             ('G_synthesis_1/4x4/Conv/bias', 'G_synthesis/4x4/Conv/bias'),
             ('G_synthesis_1/4x4/Conv/StyleMod/weight',
              'G_synthesis/4x4/Conv/StyleMod/weight'),
             ('G_synthesis_1/4x4/Conv/StyleMod/bias',
              'G_synthesis/4x4/Conv/StyleMod/bias'),
             ('G_synthesis_1/ToRGB_lod7/weight',
              'G_synthesis/ToRGB_lod7/weight'),
             ('G_synthesis_1/ToRGB_lod7/bias', 'G_synthesis/ToRGB_lod7/bias'),
             ('G_synthesis_1/8x8/Conv0_up/weight',
              'G_synthesis/8x8/Conv0_up/weight'),
             ('G_synthesis_1/8x8/Conv0_up/Noise/weight',
              'G_synthesis/8x8/Conv0_up/Noise/weight'),
             ('G_synthesis_1/8x8/Conv0_up/bias',
              'G_synthesis/8x8/Conv0_up/bias'),
             ('G_synthesis_1/8x8/Conv0_up/StyleMod/weight',
              'G_synthesis/8x8/Conv0_up/StyleMod/weight'),
             ('G_synthesis_1/8x8/Conv0_up/StyleMod/bias',
              'G_synthesis/8x8/Conv0_up/StyleMod/bias'),
             ('G_synthesis_1/8x8/Conv1/weight',
              'G_synthesis/8x8/Conv1/weight'),
             ('G_synthesis_1/8x8/Conv1/Noise/weight',
              'G_synthesis/8x8/Conv1/Noise/weight'),
             ('G_synthesis_1/8x8/Conv1/bias', 'G_synthesis/8x8/Conv1/bias'),
             ('G_synthesis_1/8x8/Conv1/StyleMod/weight',
              'G_synthesis/8x8/Conv1/StyleMod/weight'),
             ('G_synthesis_1/8x8/Conv1/StyleMod/bias',
              'G_synthesis/8x8/Conv1/StyleMod/bias'),
             ('G_synthesis_1/ToRGB_lod6/weight',
              'G_synthesis/ToRGB_lod6/weight'),
             ('G_synthesis_1/ToRGB_lod6/bias', 'G_synthesis/ToRGB_lod6/bias'),
             ('G_synthesis_1/16x16/Conv0_up/weight',
              'G_synthesis/16x16/Conv0_up/weight'),
             ('G_synthesis_1/16x16/Conv0_up/Noise/weight',
              'G_synthesis/16x16/Conv0_up/Noise/weight'),
             ('G_synthesis_1/16x16/Conv0_up/bias',
              'G_synthesis/16x16/Conv0_up/bias'),
             ('G_synthesis_1/16x16/Conv0_up/StyleMod/weight',
              'G_synthesis/16x16/Conv0_up/StyleMod/weight'),
             ('G_synthesis_1/16x16/Conv0_up/StyleMod/bias',
              'G_synthesis/16x16/Conv0_up/StyleMod/bias'),
             ('G_synthesis_1/16x16/Conv1/weight',
              'G_synthesis/16x16/Conv1/weight'),
             ('G_synthesis_1/16x16/Conv1/Noise/weight',
              'G_synthesis/16x16/Conv1/Noise/weight'),
             ('G_synthesis_1/16x16/Conv1/bias',
              'G_synthesis/16x16/Conv1/bias'),
             ('G_synthesis_1/16x16/Conv1/StyleMod/weight',
              'G_synthesis/16x16/Conv1/StyleMod/weight'),
             ('G_synthesis_1/16x16/Conv1/StyleMod/bias',
              'G_synthesis/16x16/Conv1/StyleMod/bias'),
             ('G_synthesis_1/ToRGB_lod5/weight',
              'G_synthesis/ToRGB_lod5/weight'),
             ('G_synthesis_1/ToRGB_lod5/bias', 'G_synthesis/ToRGB_lod5/bias'),
             ('G_synthesis_1/32x32/Conv0_up/weight',
              'G_synthesis/32x32/Conv0_up/weight'),
             ('G_synthesis_1/32x32/Conv0_up/Noise/weight',
              'G_synthesis/32x32/Conv0_up/Noise/weight'),
             ('G_synthesis_1/32x32/Conv0_up/bias',
              'G_synthesis/32x32/Conv0_up/bias'),
             ('G_synthesis_1/32x32/Conv0_up/StyleMod/weight',
              'G_synthesis/32x32/Conv0_up/StyleMod/weight'),
             ('G_synthesis_1/32x32/Conv0_up/StyleMod/bias',
              'G_synthesis/32x32/Conv0_up/StyleMod/bias'),
             ('G_synthesis_1/32x32/Conv1/weight',
              'G_synthesis/32x32/Conv1/weight'),
             ('G_synthesis_1/32x32/Conv1/Noise/weight',
              'G_synthesis/32x32/Conv1/Noise/weight'),
             ('G_synthesis_1/32x32/Conv1/bias',
              'G_synthesis/32x32/Conv1/bias'),
             ('G_synthesis_1/32x32/Conv1/StyleMod/weight',
              'G_synthesis/32x32/Conv1/StyleMod/weight'),
             ('G_synthesis_1/32x32/Conv1/StyleMod/bias',
              'G_synthesis/32x32/Conv1/StyleMod/bias'),
             ('G_synthesis_1/ToRGB_lod4/weight',
              'G_synthesis/ToRGB_lod4/weight'),
             ('G_synthesis_1/ToRGB_lod4/bias', 'G_synthesis/ToRGB_lod4/bias'),
             ('G_synthesis_1/64x64/Conv0_up/weight',
              'G_synthesis/64x64/Conv0_up/weight'),
             ('G_synthesis_1/64x64/Conv0_up/Noise/weight',
              'G_synthesis/64x64/Conv0_up/Noise/weight'),
             ('G_synthesis_1/64x64/Conv0_up/bias',
              'G_synthesis/64x64/Conv0_up/bias'),
             ('G_synthesis_1/64x64/Conv0_up/StyleMod/weight',
              'G_synthesis/64x64/Conv0_up/StyleMod/weight'),
             ('G_synthesis_1/64x64/Conv0_up/StyleMod/bias',
              'G_synthesis/64x64/Conv0_up/StyleMod/bias'),
             ('G_synthesis_1/64x64/Conv1/weight',
              'G_synthesis/64x64/Conv1/weight'),
             ('G_synthesis_1/64x64/Conv1/Noise/weight',
              'G_synthesis/64x64/Conv1/Noise/weight'),
             ('G_synthesis_1/64x64/Conv1/bias',
              'G_synthesis/64x64/Conv1/bias'),
             ('G_synthesis_1/64x64/Conv1/StyleMod/weight',
              'G_synthesis/64x64/Conv1/StyleMod/weight'),
             ('G_synthesis_1/64x64/Conv1/StyleMod/bias',
              'G_synthesis/64x64/Conv1/StyleMod/bias'),
             ('G_synthesis_1/ToRGB_lod3/weight',
              'G_synthesis/ToRGB_lod3/weight'),
             ('G_synthesis_1/ToRGB_lod3/bias', 'G_synthesis/ToRGB_lod3/bias'),
             ('G_synthesis_1/128x128/Conv0_up/weight',
              'G_synthesis/128x128/Conv0_up/weight'),
             ('G_synthesis_1/128x128/Conv0_up/Noise/weight',
              'G_synthesis/128x128/Conv0_up/Noise/weight'),
             ('G_synthesis_1/128x128/Conv0_up/bias',
              'G_synthesis/128x128/Conv0_up/bias'),
             ('G_synthesis_1/128x128/Conv0_up/StyleMod/weight',
              'G_synthesis/128x128/Conv0_up/StyleMod/weight'),
             ('G_synthesis_1/128x128/Conv0_up/StyleMod/bias',
              'G_synthesis/128x128/Conv0_up/StyleMod/bias'),
             ('G_synthesis_1/128x128/Conv1/weight',
              'G_synthesis/128x128/Conv1/weight'),
             ('G_synthesis_1/128x128/Conv1/Noise/weight',
              'G_synthesis/128x128/Conv1/Noise/weight'),
             ('G_synthesis_1/128x128/Conv1/bias',
              'G_synthesis/128x128/Conv1/bias'),
             ('G_synthesis_1/128x128/Conv1/StyleMod/weight',
              'G_synthesis/128x128/Conv1/StyleMod/weight'),
             ('G_synthesis_1/128x128/Conv1/StyleMod/bias',
              'G_synthesis/128x128/Conv1/StyleMod/bias'),
             ('G_synthesis_1/ToRGB_lod2/weight',
              'G_synthesis/ToRGB_lod2/weight'),
             ('G_synthesis_1/ToRGB_lod2/bias', 'G_synthesis/ToRGB_lod2/bias'),
             ('G_synthesis_1/256x256/Conv0_up/weight',
              'G_synthesis/256x256/Conv0_up/weight'),
             ('G_synthesis_1/256x256/Conv0_up/Noise/weight',
              'G_synthesis/256x256/Conv0_up/Noise/weight'),
             ('G_synthesis_1/256x256/Conv0_up/bias',
              'G_synthesis/256x256/Conv0_up/bias'),
             ('G_synthesis_1/256x256/Conv0_up/StyleMod/weight',
              'G_synthesis/256x256/Conv0_up/StyleMod/weight'),
             ('G_synthesis_1/256x256/Conv0_up/StyleMod/bias',
              'G_synthesis/256x256/Conv0_up/StyleMod/bias'),
             ('G_synthesis_1/256x256/Conv1/weight',
              'G_synthesis/256x256/Conv1/weight'),
             ('G_synthesis_1/256x256/Conv1/Noise/weight',
              'G_synthesis/256x256/Conv1/Noise/weight'),
             ('G_synthesis_1/256x256/Conv1/bias',
              'G_synthesis/256x256/Conv1/bias'),
             ('G_synthesis_1/256x256/Conv1/StyleMod/weight',
              'G_synthesis/256x256/Conv1/StyleMod/weight'),
             ('G_synthesis_1/256x256/Conv1/StyleMod/bias',
              'G_synthesis/256x256/Conv1/StyleMod/bias'),
             ('G_synthesis_1/ToRGB_lod1/weight',
              'G_synthesis/ToRGB_lod1/weight'),
             ('G_synthesis_1/ToRGB_lod1/bias', 'G_synthesis/ToRGB_lod1/bias'),
             ('G_synthesis_1/512x512/Conv0_up/weight',
              'G_synthesis/512x512/Conv0_up/weight'),
             ('G_synthesis_1/512x512/Conv0_up/Noise/weight',
              'G_synthesis/512x512/Conv0_up/Noise/weight'),
             ('G_synthesis_1/512x512/Conv0_up/bias',
              'G_synthesis/512x512/Conv0_up/bias'),
             ('G_synthesis_1/512x512/Conv0_up/StyleMod/weight',
              'G_synthesis/512x512/Conv0_up/StyleMod/weight'),
             ('G_synthesis_1/512x512/Conv0_up/StyleMod/bias',
              'G_synthesis/512x512/Conv0_up/StyleMod/bias'),
             ('G_synthesis_1/512x512/Conv1/weight',
              'G_synthesis/512x512/Conv1/weight'),
             ('G_synthesis_1/512x512/Conv1/Noise/weight',
              'G_synthesis/512x512/Conv1/Noise/weight'),
             ('G_synthesis_1/512x512/Conv1/bias',
              'G_synthesis/512x512/Conv1/bias'),
             ('G_synthesis_1/512x512/Conv1/StyleMod/weight',
              'G_synthesis/512x512/Conv1/StyleMod/weight'),
             ('G_synthesis_1/512x512/Conv1/StyleMod/bias',
              'G_synthesis/512x512/Conv1/StyleMod/bias'),
             ('G_synthesis_1/ToRGB_lod0/weight',
              'G_synthesis/ToRGB_lod0/weight'),
             ('G_synthesis_1/ToRGB_lod0/bias', 'G_synthesis/ToRGB_lod0/bias'),
             ('G_mapping_1/Dense0/weight', 'G_mapping/Dense0/weight'),
             ('G_mapping_1/Dense0/bias', 'G_mapping/Dense0/bias'),
             ('G_mapping_1/Dense1/weight', 'G_mapping/Dense1/weight'),
             ('G_mapping_1/Dense1/bias', 'G_mapping/Dense1/bias'),
             ('G_mapping_1/Dense2/weight', 'G_mapping/Dense2/weight'),
             ('G_mapping_1/Dense2/bias', 'G_mapping/Dense2/bias'),
             ('G_mapping_1/Dense3/weight', 'G_mapping/Dense3/weight'),
             ('G_mapping_1/Dense3/bias', 'G_mapping/Dense3/bias'),
             ('G_mapping_1/Dense4/weight', 'G_mapping/Dense4/weight'),
             ('G_mapping_1/Dense4/bias', 'G_mapping/Dense4/bias'),
             ('G_mapping_1/Dense5/weight', 'G_mapping/Dense5/weight'),
             ('G_mapping_1/Dense5/bias', 'G_mapping/Dense5/bias'),
             ('G_mapping_1/Dense6/weight', 'G_mapping/Dense6/weight'),
             ('G_mapping_1/Dense6/bias', 'G_mapping/Dense6/bias'),
             ('G_mapping_1/Dense7/weight', 'G_mapping/Dense7/weight'),
             ('G_mapping_1/Dense7/bias', 'G_mapping/Dense7/bias')])
